import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:sum_enterprises/core/constants/app_constants.dart';
import 'package:sum_enterprises/core/widgets/custom_button.dart';
import 'package:sum_enterprises/features/auth/domain/models/user_model.dart';
import 'package:sum_enterprises/features/employee/presentation/providers/employee_provider.dart';

/// Screen allowing administrators to register new employee credentials.
/// Implements input validation, auto-generated sequence IDs, M3 styling and focus traversal.
class AddEmployeeScreen extends ConsumerStatefulWidget {
  const AddEmployeeScreen({super.key});

  @override
  ConsumerState<AddEmployeeScreen> createState() => _AddEmployeeScreenState();
}

class _AddEmployeeScreenState extends ConsumerState<AddEmployeeScreen> {
  final _formKey = GlobalKey<FormState>();

  // Text Controllers
  final _nameController = TextEditingController();
  final _employeeIdController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _designationController = TextEditingController();
  final _passwordController = TextEditingController();

  // Selected values
  String? _selectedDepartment;
  DateTime? _selectedJoiningDate;
  bool _obscurePassword = true;
  bool _hasAutoGeneratedId = false;

  // Focus Nodes
  final _nameFocusNode = FocusNode();
  final _employeeIdFocusNode = FocusNode();
  final _emailFocusNode = FocusNode();
  final _phoneFocusNode = FocusNode();
  final _designationFocusNode = FocusNode();
  final _passwordFocusNode = FocusNode();

  // Predefined departments
  final List<String> _departments = [
    'Operations',
    'Technical & IT',
    'Human Resources',
    'Sales & Marketing',
    'Finance',
    'Administration',
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _employeeIdController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _designationController.dispose();
    _passwordController.dispose();

    _nameFocusNode.dispose();
    _employeeIdFocusNode.dispose();
    _emailFocusNode.dispose();
    _phoneFocusNode.dispose();
    _designationFocusNode.dispose();
    _passwordFocusNode.dispose();
    super.dispose();
  }

  /// Calculates and fills the next sequential Employee ID based on active stream registers
  void _autoGenerateIdIfNeeded(List<UserModel> employees) {
    if (_hasAutoGeneratedId || _employeeIdController.text.isNotEmpty) return;

    int maxNumber = 1000;
    final regex = RegExp(r'SUM-(\d+)');
    
    for (final emp in employees) {
      final match = regex.firstMatch(emp.employeeId);
      if (match != null) {
        final number = int.tryParse(match.group(1) ?? '');
        if (number != null && number > maxNumber) {
          maxNumber = number;
        }
      }
    }

    setState(() {
      _employeeIdController.text = 'SUM-${maxNumber + 1}';
      _hasAutoGeneratedId = true;
    });
  }

  /// Shows DatePicker to select the joining date
  Future<void> _selectJoiningDate(BuildContext context) async {
    FocusScope.of(context).unfocus();
    final DateTime initialDate = _selectedJoiningDate ?? DateTime.now();
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: initialDate,
      firstDate: DateTime(2020),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );

    if (picked != null && picked != _selectedJoiningDate) {
      setState(() {
        _selectedJoiningDate = picked;
      });
    }
  }

  void _submitForm(List<UserModel> existingEmployees) {
    if (_formKey.currentState?.validate() ?? false) {
      FocusScope.of(context).unfocus();

      // Client-side uniqueness checks
      final inputEmail = _emailController.text.trim().toLowerCase();
      final inputEmpId = _employeeIdController.text.trim().toUpperCase();

      final emailExists = existingEmployees.any((e) => e.email.toLowerCase() == inputEmail);
      if (emailExists) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('This email address is already registered.'),
            backgroundColor: Colors.red,
            behavior: SnackBarBehavior.floating,
          ),
        );
        return;
      }

      final empIdExists = existingEmployees.any((e) => e.employeeId.toUpperCase() == inputEmpId);
      if (empIdExists) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('This Employee ID is already registered.'),
            backgroundColor: Colors.red,
            behavior: SnackBarBehavior.floating,
          ),
        );
        return;
      }

      // Build model skeleton
      final newEmployee = UserModel(
        uid: '', // Managed by auth registration implementation
        email: inputEmail,
        fullName: _nameController.text.trim(),
        role: UserRole.employee,
        phoneNumber: _phoneController.text.trim(),
        designation: _designationController.text.trim(),
        department: _selectedDepartment,
        joiningDate: _selectedJoiningDate ?? DateTime.now(),
        isActive: true,
      );

      // Trigger Riverpod controller
      ref.read(employeeActionControllerProvider.notifier).registerEmployee(
            employee: newEmployee,
            password: _passwordController.text,
          );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final actionState = ref.watch(employeeActionControllerProvider);
    final employeesAsync = ref.watch(employeeListStreamProvider);

    // Dynamic auto-generation hook watching loaded employees
    employeesAsync.whenData((employees) {
      _autoGenerateIdIfNeeded(employees);
    });

    final List<UserModel> existingEmployees = employeesAsync.value ?? [];

    // Reactive navigation/messaging listener
    ref.listen<EmployeeActionState>(employeeActionControllerProvider, (previous, next) {
      if (next.isSuccess && next.successMessage != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            key: const ValueKey('add_employee_success_snackbar'),
            content: Row(
              children: [
                const Icon(Icons.check_circle_rounded, color: Colors.white),
                const SizedBox(width: 8),
                Expanded(child: Text(next.successMessage!)),
              ],
            ),
            backgroundColor: Colors.green,
            behavior: SnackBarBehavior.floating,
          ),
        );
        ref.read(employeeActionControllerProvider.notifier).clearMessages();
        context.pop(); // Navigate back
      } else if (next.errorMessage != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            key: const ValueKey('add_employee_error_snackbar'),
            content: Row(
              children: [
                const Icon(Icons.error_outline_rounded, color: Colors.white),
                const SizedBox(width: 8),
                Expanded(child: Text(next.errorMessage!)),
              ],
            ),
            backgroundColor: theme.colorScheme.error,
            behavior: SnackBarBehavior.floating,
          ),
        );
        ref.read(employeeActionControllerProvider.notifier).clearMessages();
      }
    });

    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
        key: const ValueKey('add_employee_scaffold'),
        appBar: AppBar(
          key: const ValueKey('add_employee_app_bar'),
          title: const Text('Register Employee'),
          centerTitle: true,
        ),
        body: SafeArea(
          child: LayoutBuilder(
            builder: (context, constraints) {
              return SingleChildScrollView(
                key: const ValueKey('add_employee_scroll'),
                padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 20.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // Photo Placeholder Avatar
                      Center(
                        child: Stack(
                          children: [
                            CircleAvatar(
                              radius: 46,
                              backgroundColor: theme.colorScheme.primary.withOpacity(0.08),
                              child: Icon(
                                Icons.person_rounded,
                                size: 52,
                                color: theme.colorScheme.primary,
                              ),
                            ),
                            Positioned(
                              bottom: 0,
                              right: 0,
                              child: CircleAvatar(
                                radius: 16,
                                backgroundColor: theme.colorScheme.primary,
                                child: const Icon(
                                  Icons.add_a_photo_rounded,
                                  size: 14,
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 32),

                      // Full Name
                      TextFormField(
                        key: const ValueKey('field_full_name'),
                        controller: _nameController,
                        focusNode: _nameFocusNode,
                        autofillHints: const [AutofillHints.name],
                        textInputAction: TextInputAction.next,
                        onFieldSubmitted: (_) => FocusScope.of(context).requestFocus(_employeeIdFocusNode),
                        validator: (val) {
                          if (val == null || val.trim().isEmpty) {
                            return 'Please enter the full name.';
                          }
                          return null;
                        },
                        decoration: InputDecoration(
                          labelText: 'Full Name',
                          prefixIcon: const Icon(Icons.person_outline_rounded),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 18),

                      // Employee ID
                      TextFormField(
                        key: const ValueKey('field_employee_id'),
                        controller: _employeeIdController,
                        focusNode: _employeeIdFocusNode,
                        textInputAction: TextInputAction.next,
                        onFieldSubmitted: (_) => FocusScope.of(context).requestFocus(_emailFocusNode),
                        validator: (val) {
                          if (val == null || val.trim().isEmpty) {
                            return 'Please enter the Employee ID.';
                          }
                          final inputId = val.trim().toUpperCase();
                          if (existingEmployees.any((e) => e.employeeId.toUpperCase() == inputId)) {
                            return 'Employee ID already exists.';
                          }
                          return null;
                        },
                        decoration: InputDecoration(
                          labelText: 'Employee ID',
                          prefixIcon: const Icon(Icons.badge_outlined),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          suffixIcon: IconButton(
                            icon: const Icon(Icons.refresh_rounded),
                            tooltip: 'Regenerate ID',
                            onPressed: () {
                              _hasAutoGeneratedId = false;
                              _employeeIdController.clear();
                              _autoGenerateIdIfNeeded(existingEmployees);
                            },
                          ),
                        ),
                      ),
                      const SizedBox(height: 18),

                      // Corporate Email
                      TextFormField(
                        key: const ValueKey('field_email'),
                        controller: _emailController,
                        focusNode: _emailFocusNode,
                        keyboardType: TextInputType.emailAddress,
                        autofillHints: const [AutofillHints.email],
                        textInputAction: TextInputAction.next,
                        onFieldSubmitted: (_) => FocusScope.of(context).requestFocus(_phoneFocusNode),
                        validator: (val) {
                          if (val == null || val.trim().isEmpty) {
                            return 'Please enter the corporate email.';
                          }
                          final emailRegex = RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$');
                          if (!emailRegex.hasMatch(val.trim())) {
                            return 'Please enter a valid email address.';
                          }
                          final inputEmail = val.trim().toLowerCase();
                          if (existingEmployees.any((e) => e.email.toLowerCase() == inputEmail)) {
                            return 'This email address is already registered.';
                          }
                          return null;
                        },
                        decoration: InputDecoration(
                          labelText: 'Corporate Email',
                          prefixIcon: const Icon(Icons.email_outlined),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 18),

                      // Phone Number
                      TextFormField(
                        key: const ValueKey('field_phone'),
                        controller: _phoneController,
                        focusNode: _phoneFocusNode,
                        keyboardType: TextInputType.phone,
                        autofillHints: const [AutofillHints.telephoneNumber],
                        textInputAction: TextInputAction.next,
                        onFieldSubmitted: (_) => FocusScope.of(context).requestFocus(_designationFocusNode),
                        validator: (val) {
                          if (val == null || val.trim().isEmpty) {
                            return 'Please enter the phone number.';
                          }
                          final phoneRegex = RegExp(r'^\+?[0-9]{7,15}$');
                          if (!phoneRegex.hasMatch(val.trim())) {
                            return 'Please enter a valid phone number (e.g. +91XXXXXXXXXX).';
                          }
                          return null;
                        },
                        decoration: InputDecoration(
                          labelText: 'Phone Number',
                          prefixIcon: const Icon(Icons.phone_outlined),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 18),

                      // Department Selector Dropdown
                      DropdownButtonFormField<String>(
                        key: const ValueKey('field_department'),
                        value: _selectedDepartment,
                        decoration: InputDecoration(
                          labelText: 'Department',
                          prefixIcon: const Icon(Icons.corporate_fare_rounded),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                        items: _departments.map((dept) {
                          return DropdownMenuItem<String>(
                            value: dept,
                            child: Text(dept),
                          );
                        }).toList(),
                        onChanged: (val) {
                          setState(() {
                            _selectedDepartment = val;
                          });
                        },
                        validator: (val) {
                          if (val == null || val.isEmpty) {
                            return 'Please select a department.';
                          }
                          return null;
                        },
                      ),
                      const SizedBox(height: 18),

                      // Designation
                      TextFormField(
                        key: const ValueKey('field_designation'),
                        controller: _designationController,
                        focusNode: _designationFocusNode,
                        textInputAction: TextInputAction.next,
                        onFieldSubmitted: (_) => FocusScope.of(context).requestFocus(_passwordFocusNode),
                        validator: (val) {
                          if (val == null || val.trim().isEmpty) {
                            return 'Please enter the designation.';
                          }
                          return null;
                        },
                        decoration: InputDecoration(
                          labelText: 'Designation',
                          prefixIcon: const Icon(Icons.work_outline_rounded),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 18),

                      // Joining Date Selector
                      InkWell(
                        key: const ValueKey('field_joining_date'),
                        onTap: () => _selectJoiningDate(context),
                        borderRadius: BorderRadius.circular(12),
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 16),
                          decoration: BoxDecoration(
                            border: Border.all(color: theme.colorScheme.onSurface.withOpacity(0.38)),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Row(
                            children: [
                              Icon(Icons.calendar_month_outlined, color: theme.colorScheme.onSurfaceVariant),
                              const SizedBox(width: 12),
                              Expanded(
                                child: Text(
                                  _selectedJoiningDate != null
                                      ? DateFormat('dd MMMM yyyy').format(_selectedJoiningDate!)
                                      : 'Select Joining Date',
                                  style: TextStyle(
                                    fontSize: 16,
                                    color: _selectedJoiningDate != null
                                        ? theme.colorScheme.onSurface
                                        : theme.colorScheme.onSurfaceVariant,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 18),

                      // Initial Password
                      TextFormField(
                        key: const ValueKey('field_password'),
                        controller: _passwordController,
                        focusNode: _passwordFocusNode,
                        obscureText: _obscurePassword,
                        autofillHints: const [AutofillHints.newPassword],
                        textInputAction: TextInputAction.done,
                        onFieldSubmitted: (_) => _submitForm(existingEmployees),
                        validator: (val) {
                          if (val == null || val.isEmpty) {
                            return 'Please enter the initial password.';
                          }
                          if (val.length < 8) {
                            return 'Password must be at least 8 characters long.';
                          }
                          return null;
                        },
                        decoration: InputDecoration(
                          labelText: 'Initial Password',
                          prefixIcon: const Icon(Icons.lock_outline_rounded),
                          suffixIcon: IconButton(
                            icon: Icon(
                              _obscurePassword ? Icons.visibility_off_outlined : Icons.visibility_outlined,
                            ),
                            onPressed: () {
                              setState(() {
                                _obscurePassword = !_obscurePassword;
                              });
                            },
                          ),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 36),

                      // Large submit button
                      CustomButton(
                        key: const ValueKey('btn_create_employee'),
                        text: 'CREATE EMPLOYEE ACCOUNT',
                        icon: Icons.person_add_rounded,
                        isLoading: actionState.isLoading,
                        onPressed: actionState.isLoading
                            ? null
                            : () => _submitForm(existingEmployees),
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
