// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2TE7zxqkDX5jSmwlTMuPIql6uR_mU0A',
    appId: '1:751052003174:web:311d4ecde0b20deca15aa7',
    messagingSenderId: '751052003174',
    projectId: 'sum-enterprises',
    authDomain: 'sum-enterprises.firebaseapp.com',
    storageBucket: 'sum-enterprises.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACz8rO5sRxgSWL9G6_3jZnD9PVGyOcog',
    appId: '1:751052003174:android:86f06bad9a309f51a15aa7',
    messagingSenderId: '751052003174',
    projectId: 'sum-enterprises',
    storageBucket: 'sum-enterprises.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAg7GsA2HJyjMPHIAEw3S2tuKHPHO6GfM',
    appId: '1:751052003174:ios:f4784d5e6316ee5aa15aa7',
    messagingSenderId: '751052003174',
    projectId: 'sum-enterprises',
    storageBucket: 'sum-enterprises.firebasestorage.app',
    iosBundleId: 'com.example.sumEnterprises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAg7GsA2HJyjMPHIAEw3S2tuKHPHO6GfM',
    appId: '1:751052003174:ios:f4784d5e6316ee5aa15aa7',
    messagingSenderId: '751052003174',
    projectId: 'sum-enterprises',
    storageBucket: 'sum-enterprises.firebasestorage.app',
    iosBundleId: 'com.example.sumEnterprises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi2TE7zxqkDX5jSmwlTMuPIql6uR_mU0A',
    appId: '1:751052003174:web:f98bf8a3a94fcc7ba15aa7',
    messagingSenderId: '751052003174',
    projectId: 'sum-enterprises',
    authDomain: 'sum-enterprises.firebaseapp.com',
    storageBucket: 'sum-enterprises.firebasestorage.app',
  );
}
